// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTg3KdT6tOds22FFrShteJNiqBdx-SKyM',
    appId: '1:860330144105:web:7508a6f91c1f33b8440df8',
    messagingSenderId: '860330144105',
    projectId: 'chat-app-1e23a',
    authDomain: 'chat-app-1e23a.firebaseapp.com',
    storageBucket: 'chat-app-1e23a.appspot.com',
    measurementId: 'G-HNDKBFF20E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEW-HL9OHMDNMWztCWUKhrw83ZynyC-Bw',
    appId: '1:860330144105:android:d67201cbc1449fbe440df8',
    messagingSenderId: '860330144105',
    projectId: 'chat-app-1e23a',
    storageBucket: 'chat-app-1e23a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2AezEcZ27IyS3cNlE9xDppgIm55ClMA',
    appId: '1:860330144105:ios:21d2e9fe860453b3440df8',
    messagingSenderId: '860330144105',
    projectId: 'chat-app-1e23a',
    storageBucket: 'chat-app-1e23a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW2AezEcZ27IyS3cNlE9xDppgIm55ClMA',
    appId: '1:860330144105:ios:21d2e9fe860453b3440df8',
    messagingSenderId: '860330144105',
    projectId: 'chat-app-1e23a',
    storageBucket: 'chat-app-1e23a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTg3KdT6tOds22FFrShteJNiqBdx-SKyM',
    appId: '1:860330144105:web:0855b2cd70b3a3d1440df8',
    messagingSenderId: '860330144105',
    projectId: 'chat-app-1e23a',
    authDomain: 'chat-app-1e23a.firebaseapp.com',
    storageBucket: 'chat-app-1e23a.appspot.com',
    measurementId: 'G-8PT9G7STC8',
  );
}
